import { describe, expect, it } from "vitest";

import { resolveVendorRef } from "./vendor-expressions-ref";

const STAMP = [
  "# Generated by scripts/vendor-expressions.ts. Do not edit src/expressions/lang by hand.",
  "source: https://github.com/flanksource/gomplate.git",
  "commit: a16dac476d774bd27c6ae1111643fc0612cc0740",
  "",
].join("\n");

describe("resolveVendorRef", () => {
  it("checks the committed tree against the exact source revision recorded in VENDOR", () => {
    expect(resolveVendorRef({ check: true, stamp: STAMP })).toBe(
      "a16dac476d774bd27c6ae1111643fc0612cc0740",
    );
  });

  it("vendors the latest main revision by default", () => {
    expect(resolveVendorRef({ check: false, stamp: STAMP })).toBe("main");
  });

  it("honors an explicit source revision in either mode", () => {
    expect(resolveVendorRef({ check: true, explicitRef: "v4.0.0", stamp: STAMP })).toBe(
      "v4.0.0",
    );
  });

  it("fails when check mode has no exact recorded revision", () => {
    expect(() => resolveVendorRef({ check: true, stamp: "commit: main\n" })).toThrow(
      "VENDOR must record an exact 40-character commit for --check",
    );
  });
});
