/**
 * Vendors the language definitions from gomplate.
 *
 * The tokenizers are generated from cel-go's ANTLR grammar, `text/template`'s
 * lexer and gomplate's live function registries — none of which exist outside a
 * Go toolchain. Rather than reimplement any of that here, this clones gomplate,
 * runs its generator, and commits the result. gomplate stays the single source
 * of truth; this package is how it reaches npm, because clicky-ui is where the
 * publish credentials live.
 *
 * The whole `src` tree is copied, not just the generated files: the completion,
 * hover and path-expression runtime changes with the generated shape, and
 * maintaining a second copy of it here would drift within a release.
 *
 *   pnpm vendor                          # from github.com/flanksource/gomplate@main
 *   pnpm vendor --ref v3.2.0             # from a tag
 *   pnpm vendor --from ../../../gomplate # from a local checkout, while iterating
 *   pnpm vendor:check                    # fail if the tree is out of date
 */
import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(packageRoot, "src", "lang");
const stamp = join(packageRoot, "VENDOR");

const DEFAULT_REMOTE = "https://github.com/flanksource/gomplate.git";
/** Where the generator writes, and where the runtime lives, inside gomplate. */
const SOURCE_SUBPATH = join("web", "packages", "lang", "src");
const GENERATED_SUBPATH = join(SOURCE_SUBPATH, "generated");

interface Args {
  from: string;
  ref: string;
  check: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { from: DEFAULT_REMOTE, ref: "main", check: false };
  for (let i = 0; i < argv.length; i += 1) {
    const flag = argv[i];
    if (flag === "--check") args.check = true;
    else if (flag === "--from") args.from = argv[(i += 1)] ?? args.from;
    else if (flag === "--ref") args.ref = argv[(i += 1)] ?? args.ref;
    else throw new Error(`unknown argument ${flag}`);
  }
  return args;
}

function run(command: string, commandArgs: string[], cwd: string) {
  execFileSync(command, commandArgs, { cwd, stdio: "inherit" });
}

function capture(command: string, commandArgs: string[], cwd: string) {
  return execFileSync(command, commandArgs, { cwd, encoding: "utf8" }).trim();
}

/** Returns the checkout to generate from, and a cleanup for it. */
function checkout(args: Args): { dir: string; cleanup: () => void } {
  const local = resolve(packageRoot, args.from);
  if (existsSync(join(local, "go.mod"))) {
    // A local checkout is used in place, not copied: the point of --from is to
    // see uncommitted generator changes before they are pushed.
    console.log(`[vendor] using local checkout ${local}`);
    return { dir: local, cleanup: () => {} };
  }

  const dir = mkdtempSync(join(tmpdir(), "gomplate-vendor-"));
  console.log(`[vendor] cloning ${args.from}@${args.ref}`);
  run("git", ["clone", "--depth", "1", "--branch", args.ref, args.from, dir], packageRoot);
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function describe(dir: string): string {
  const sha = capture("git", ["rev-parse", "HEAD"], dir);
  const dirty = capture("git", ["status", "--porcelain"], dir) !== "";
  return dirty ? `${sha} (dirty working tree)` : sha;
}

function vendor(args: Args, destination: string) {
  const { dir, cleanup } = checkout(args);
  try {
    console.log("[vendor] running genmonarch");
    run("go", ["run", "./cmd/genmonarch", "-out", join(dir, GENERATED_SUBPATH)], dir);

    rmSync(destination, { recursive: true, force: true });
    cpSync(join(dir, SOURCE_SUBPATH), destination, { recursive: true });
    return describe(dir);
  } finally {
    cleanup();
  }
}

function stampFor(source: string, args: Args) {
  return [
    "# Generated by scripts/vendor-lang.ts. Do not edit src/lang by hand.",
    `source: ${args.from}`,
    `commit: ${source}`,
    "",
  ].join("\n");
}

const args = parseArgs(process.argv.slice(2));

if (!args.check) {
  const source = vendor(args, target);
  writeFileSync(stamp, stampFor(source, args));
  console.log(`[vendor] vendored ${source}`);
} else {
  // Regenerate into a scratch directory and compare, so a hand-edit under
  // src/lang or a stale vendoring fails CI rather than shipping.
  const scratch = mkdtempSync(join(tmpdir(), "gomplate-vendor-check-"));
  try {
    const fresh = join(scratch, "lang");
    vendor(args, fresh);

    const diff = diffTrees(target, fresh);
    if (diff.length > 0) {
      console.error("[vendor] src/lang is out of date or has been edited by hand:");
      for (const path of diff.slice(0, 20)) console.error(`  ${path}`);
      if (diff.length > 20) console.error(`  … and ${diff.length - 20} more`);
      console.error("[vendor] run `pnpm vendor` and commit the result.");
      process.exit(1);
    }
    console.log("[vendor] src/lang is up to date");
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

/** Paths that differ between two trees, in either direction. */
function diffTrees(a: string, b: string): string[] {
  const files = new Set([...listFiles(a), ...listFiles(b)]);
  const differing: string[] = [];
  for (const relative of [...files].sort()) {
    const left = readIfPresent(join(a, relative));
    const right = readIfPresent(join(b, relative));
    if (left !== right) differing.push(relative);
  }
  return differing;
}

function listFiles(root: string, prefix = ""): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...listFiles(join(root, entry.name), relative));
    else out.push(relative);
  }
  return out;
}

function readIfPresent(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}
