import type { Approval, ApprovalCheck, ApprovalIconKey } from "./types";

const ok = (
  icon: ApprovalIconKey,
  title: string,
  detail: string,
): ApprovalCheck => ({ tone: "ok", icon, title, detail });
const pending = (
  icon: ApprovalIconKey,
  title: string,
  detail: string,
): ApprovalCheck => ({ tone: "pending", icon, title, detail });
const bad = (
  icon: ApprovalIconKey,
  title: string,
  detail: string,
): ApprovalCheck => ({ tone: "bad", icon, title, detail });

/**
 * Every change awaiting approval, across kinds: journal, transaction, account,
 * mapping and upstream (writes back to the connected system).
 */
export const APPROVALS: Approval[] = [
  {
    id: "za-itr14-tax-position~77f980298144",
    kind: "journal",
    icon: "tax",
    direction: "internal",
    title: "Current income tax FY2025",
    subtitle: "Journal · 2 lines · posts to FY2025",
    amount: 32592.17,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "za-corporate-tax",
    ruleId: "acae5f42-2dc4-57a8-b76b-f4a3f8fed170",
    ruleVersion: 1,
    targetType: "period",
    targetId: "FY2025",
    period: "FY2025",
    connector: "Xero",
    idempotency:
      "rule:eb1091264974a4fbbf8486332323a32379a7b1fc85550525abe018e9f45829c9",
    sourceRecords: ["period:FY2025"],
    requestedBy: "Rule engine",
    created: "2026-07-22 20:12:15 UTC",
    age: "5d",
    change: {
      name: "Current income tax FY2025",
      date: "2025-12-31",
      status: "Draft",
      debit: 32592.17,
      credit: 32592.17,
      lines: [
        {
          code: "505",
          name: "Income tax expense",
          cls: "expense",
          icon: "expenses",
          dir: "debit",
          desc: "Current tax charge · ITR14 computation",
          net: 32592.17,
          tax: 0,
          gross: 32592.17,
        },
        {
          code: "830",
          name: "Income tax payable",
          cls: "liability",
          icon: "ap",
          dir: "credit",
          desc: "Liability raised to SARS",
          net: -32592.17,
          tax: 0,
          gross: -32592.17,
        },
      ],
    },
    live: {
      note: "The preview was built 5 days ago against FY2025. Re-read 505 and 830 from the ledger to confirm nothing moved since — the balanced check only proves the journal is internally consistent.",
      cols: ["Account", "Ledger now", "After posting"],
      rows: [
        {
          code: "505",
          name: "Income tax expense",
          cls: "expense",
          now: 0,
          after: 32592.17,
        },
        {
          code: "830",
          name: "Income tax payable",
          cls: "liability",
          now: -4118.63,
          after: -36710.8,
        },
      ],
    },
    checks: [
      ok(
        "trial_balance",
        "Debits equal credits",
        "32,592.17 both sides across 2 lines.",
      ),
      ok(
        "paid",
        "Idempotency key unrecorded",
        "No prior posting carries this key — approval will not double-post.",
      ),
      ok(
        "rule",
        "Rule version current",
        "v1 is the active version of za-itr14-tax-position.",
      ),
      ok("opening", "FY2025 open", "Period locks 2026-09-30. 64 days of headroom."),
      pending(
        "outstanding",
        "Live state not verified",
        "Preview built 5 days ago. Re-check the ledger before approving.",
      ),
    ],
    timeline: [
      {
        icon: "rule",
        who: "Rule engine",
        what: "evaluated za-itr14-tax-position against FY2025 and proposed one journal.",
        at: "2026-07-22 20:12:15 UTC",
      },
      {
        icon: "journal",
        who: "System",
        what: "generated the journal preview — balanced, 2 lines, no tax component.",
        at: "2026-07-22 20:12:16 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy za-corporate-tax",
        what: "routed the change to approval. No named approvers resolved.",
        at: "2026-07-22 20:12:16 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "rule": "za-itr14-tax-position~77f980298144",\n  "rule_version": 1,\n  "module": "za-corporate-tax",\n  "target": { "type": "period", "id": "FY2025" },\n  "resume_policy": "approval_required",\n  "amount": "32592.17",\n  "currency": "ZAR"\n}`,
      "Preview payload": `{\n  "journal": {\n    "narration": "Current income tax FY2025",\n    "date": "2025-12-31",\n    "status": "DRAFT",\n    "lines": [\n      { "account": "505", "net": "32592.17",  "tax": "0.00", "gross": "32592.17"  },\n      { "account": "830", "net": "-32592.17", "tax": "0.00", "gross": "-32592.17" }\n    ]\n  },\n  "balanced": true\n}`,
    },
  },
  {
    id: "ar-invoice-autoraise~c41d9f2e8815",
    kind: "transaction",
    icon: "invoice",
    direction: "outbound",
    title: "Sales invoice INV-2043 · Northwind Logistics",
    subtitle: "Raise and send · net 30",
    amount: 21217.5,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "ar-billing",
    ruleId: "2b41c7de-90aa-4c11-9d3e-b5c1a4471f02",
    ruleVersion: 4,
    targetType: "contract",
    targetId: "CTR-1188",
    period: "Jun 2026",
    connector: "Xero",
    idempotency: "rule:9f3a2c14ff70b23c8f7a1e5d4b6c9081aa22ef4419c5d0b7",
    sourceRecords: ["contract:CTR-1188", "usage:2026-06"],
    requestedBy: "Rule engine",
    created: "2026-07-25 04:02:11 UTC",
    age: "2d",
    change: {
      docType: "Sales invoice",
      number: "INV-2043",
      contact: "Northwind Logistics (Pty) Ltd",
      contactRef: "CON-0442",
      date: "2026-06-30",
      due: "2026-07-30",
      status: "Draft",
      terms: "Net 30",
      lines: [
        {
          code: "200",
          name: "Sales — platform fees",
          cls: "revenue",
          icon: "income",
          desc: "Monthly platform fee · June 2026",
          qty: 1,
          unit: 14200,
          net: 14200,
          tax: 2130,
          gross: 16330,
        },
        {
          code: "260",
          name: "Sales — overage",
          cls: "revenue",
          icon: "income",
          desc: "Metered ingest · 4.25 TB over plan",
          qty: 4.25,
          unit: 1000,
          net: 4250,
          tax: 637.5,
          gross: 4887.5,
        },
      ],
      totals: { net: 18450, tax: 2767.5, gross: 21217.5 },
    },
    live: {
      note: "Confirm the customer balance and that INV-2043 has not already been raised in Xero for this contract period.",
      cols: ["Account", "Ledger now", "After posting"],
      rows: [
        {
          code: "610",
          name: "Accounts receivable",
          cls: "asset",
          now: 184220.4,
          after: 205437.9,
        },
        {
          code: "200",
          name: "Sales — platform fees",
          cls: "revenue",
          now: -1204880.0,
          after: -1223330.0,
        },
        {
          code: "820",
          name: "VAT output",
          cls: "liability",
          now: -172140.55,
          after: -174908.05,
        },
      ],
    },
    checks: [
      ok(
        "trial_balance",
        "Invoice totals reconcile",
        "Net 18,450.00 + VAT 2,767.50 = 21,217.50.",
      ),
      ok(
        "tax",
        "VAT treatment matches contact",
        "Standard rate 15% · VAT number verified 2026-04-11.",
      ),
      ok(
        "contact",
        "Contact active",
        "Northwind Logistics · no credit hold, 2 invoices open.",
      ),
      pending(
        "outstanding",
        "Will send on approve",
        "Approval raises the invoice in Xero and emails the billing contact.",
      ),
    ],
    timeline: [
      {
        icon: "rule",
        who: "Rule engine",
        what: "read June usage against contract CTR-1188 and drafted one invoice.",
        at: "2026-07-25 04:02:11 UTC",
      },
      {
        icon: "invoice",
        who: "System",
        what: "priced 2 lines from the rate card — platform fee plus 4.25 TB overage.",
        at: "2026-07-25 04:02:12 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy ar-billing",
        what: "held the invoice: value above the 20,000.00 auto-send threshold.",
        at: "2026-07-25 04:02:12 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "rule": "ar-invoice-autoraise~c41d9f2e8815",\n  "contract": "CTR-1188",\n  "usage_period": "2026-06",\n  "auto_send_threshold": "20000.00",\n  "held": true\n}`,
      "Preview payload": `{\n  "invoice": {\n    "type": "ACCREC", "number": "INV-2043", "contact": "CON-0442",\n    "date": "2026-06-30", "due": "2026-07-30",\n    "line_items": [\n      { "account": "200", "quantity": 1,    "unit": "14200.00", "tax": "OUTPUT2" },\n      { "account": "260", "quantity": 4.25, "unit": "1000.00",  "tax": "OUTPUT2" }\n    ]\n  }\n}`,
    },
  },
  {
    id: "ap-credit-note~5b7742a01c96",
    kind: "transaction",
    icon: "credit_note",
    direction: "inbound",
    title: "Credit note CN-0117 · Vodacom Business",
    subtitle: "Applies against BILL-8821",
    amount: -4738.0,
    currency: "ZAR",
    state: "proposed",
    readiness: "Blocked",
    policy: "Approval required",
    module: "ap-disputes",
    ruleId: "7c25f1b0-3ad8-4e19-8f52-19cc7f80a3de",
    ruleVersion: 2,
    targetType: "bill",
    targetId: "BILL-8821",
    period: "Jun 2026",
    connector: "Xero",
    idempotency: "rule:41ab77cc5e2f9a13d8b4076e5cf1029a7db3e4415c60ff28",
    sourceRecords: ["bill:BILL-8821", "dispute:DSP-0031"],
    requestedBy: "K. Mahlangu",
    created: "2026-07-26 11:40:02 UTC",
    age: "1d",
    change: {
      docType: "Credit note",
      number: "CN-0117",
      contact: "Vodacom Business",
      contactRef: "CON-0091",
      date: "2026-06-28",
      due: "—",
      status: "Draft",
      terms: "Applied to BILL-8821",
      lines: [
        {
          code: "489",
          name: "Telephone and internet",
          cls: "expense",
          icon: "expenses",
          desc: "Duplicate line rental · Apr–Jun",
          qty: 3,
          unit: 1373.33,
          net: 4120,
          tax: 618,
          gross: 4738,
        },
      ],
      totals: { net: 4120, tax: 618, gross: 4738 },
    },
    live: {
      note: "BILL-8821 must still be open and unreconciled for the credit to apply cleanly.",
      cols: ["Account", "Ledger now", "After posting"],
      rows: [
        {
          code: "800",
          name: "Accounts payable",
          cls: "liability",
          now: -96420.18,
          after: -91682.18,
        },
        {
          code: "489",
          name: "Telephone and internet",
          cls: "expense",
          now: 38112.4,
          after: 33992.4,
        },
      ],
    },
    checks: [
      ok(
        "trial_balance",
        "Credit totals reconcile",
        "Net 4,120.00 + VAT 618.00 = 4,738.00.",
      ),
      ok(
        "bill",
        "Target bill found",
        "BILL-8821 · 12,904.00 outstanding, not yet paid.",
      ),
      bad(
        "overdue",
        "Bill partially reconciled",
        "4,738.00 of BILL-8821 was matched to a bank line on 2026-07-19. Unmatch it, or the credit will orphan.",
      ),
      pending(
        "outstanding",
        "Supplier not notified",
        "Approval does not tell Vodacom — raise the dispute close-out separately.",
      ),
    ],
    timeline: [
      {
        icon: "contact",
        who: "K. Mahlangu",
        what: "opened dispute DSP-0031 against three months of duplicate line rental.",
        at: "2026-07-24 09:18:44 UTC",
      },
      {
        icon: "credit_note",
        who: "Rule engine",
        what: "drafted CN-0117 from the accepted dispute lines.",
        at: "2026-07-26 11:40:02 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy ap-disputes",
        what: "blocked auto-apply — target bill has a bank match.",
        at: "2026-07-26 11:40:03 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "rule": "ap-credit-note~5b7742a01c96",\n  "dispute": "DSP-0031",\n  "against": "BILL-8821",\n  "lines_accepted": 3,\n  "blocked_by": ["bank_match"]\n}`,
    },
  },
  {
    id: "coa-deferred-tax~9ac13bef2204",
    kind: "account",
    icon: "coa",
    direction: "outbound",
    title: "New account 831 · Deferred tax liability",
    subtitle: "Chart of accounts · liability",
    amount: null,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "za-corporate-tax",
    ruleId: "d10c88a4-6b7e-4a30-9c15-2f70bb9e1c45",
    ruleVersion: 1,
    targetType: "chart",
    targetId: "ZA-COA-v7",
    period: "FY2025",
    connector: "Xero",
    idempotency: "rule:c7d0f1938a4b62e5107cf3ab9d2e4477fa5b8801ce34d9a6",
    sourceRecords: ["chart:ZA-COA-v7"],
    requestedBy: "Rule engine",
    created: "2026-07-21 06:30:00 UTC",
    age: "6d",
    change: {
      op: "create",
      code: "831",
      name: "Deferred tax liability",
      cls: "liability",
      type: "Non-current liability",
      taxRate: "No VAT (0%)",
      parent: "830 · Income tax payable",
      currency: "ZAR",
      description:
        "Holds the deferred tax position raised by the ITR14 computation, separated from current tax payable.",
      flags: [
        ["Show on dashboard", "No"],
        ["Enable payments", "No"],
        ["Lock to rule postings", "Yes"],
      ],
      usedBy: [
        {
          rule: "za-itr14-tax-position",
          what: "will post the deferred portion here from FY2025 onward",
        },
        {
          rule: "za-deferred-tax-unwind",
          what: "draft rule, blocked until this account exists",
        },
      ],
    },
    live: {
      note: "Confirm 831 is unused in the live chart before creating it — a collision would silently remap postings.",
      cols: ["Check", "Ledger now", "After"],
      rows: [
        {
          code: "831",
          name: "Code availability",
          cls: "sub",
          nowText: "Unused",
          afterText: "Deferred tax liability",
        },
        {
          code: "830",
          name: "Income tax payable",
          cls: "liability",
          nowText: "No children",
          afterText: "1 child account",
        },
      ],
    },
    checks: [
      ok(
        "coa",
        "Code 831 free",
        "No account, archived or active, holds 831 in ZA-COA-v7.",
      ),
      ok(
        "trial_balance",
        "Class consistent with parent",
        "Liability under 830 · rolls into Non-current liabilities.",
      ),
      ok("tax", "Tax rate valid", "No VAT (0%) exists in the Xero tax rate list."),
      pending(
        "outstanding",
        "Writes to Xero on approve",
        "Account is created in Xero first, then mirrored into the local chart.",
      ),
    ],
    timeline: [
      {
        icon: "rule",
        who: "Rule engine",
        what: "found no account for the deferred tax position while evaluating ITR14.",
        at: "2026-07-21 06:30:00 UTC",
      },
      {
        icon: "coa",
        who: "System",
        what: "proposed 831 under 830 with the parent tax treatment.",
        at: "2026-07-21 06:30:01 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy za-corporate-tax",
        what: "chart changes always require approval.",
        at: "2026-07-21 06:30:01 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "op": "create_account",\n  "chart": "ZA-COA-v7",\n  "account": {\n    "code": "831", "name": "Deferred tax liability",\n    "class": "LIABILITY", "type": "NONCURRENTLIABILITY",\n    "tax_type": "NONE", "parent": "830"\n  }\n}`,
    },
  },
  {
    id: "map-bank-090~e21f77c4ab30",
    kind: "mapping",
    icon: "bank_rule",
    direction: "internal",
    title: "Remap bank feed 090 · 3 external accounts",
    subtitle: "Account mapping update",
    amount: null,
    currency: "ZAR",
    state: "proposed",
    readiness: "Needs review",
    policy: "Approval required",
    module: "connector-xero",
    ruleId: "5f88a012-77bd-4d99-a1c4-6ee0b2731d8a",
    ruleVersion: 9,
    targetType: "mapping",
    targetId: "XERO-ZA-MAP",
    period: "Jul 2026",
    connector: "Xero",
    idempotency: "rule:88f21c0b5d7a49e3c6041fbb27ae5390dd1c7742ab90e6f5",
    sourceRecords: ["mapping:XERO-ZA-MAP", "feed:090"],
    requestedBy: "Connector sync",
    created: "2026-07-27 03:15:20 UTC",
    age: "9h",
    change: {
      source: "Xero · bank feed 090 (FNB Business Cheque)",
      reason:
        "Xero renamed three accounts in the Jul 2026 chart sync. The connector proposes following the rename rather than orphaning the mapping.",
      rows: [
        {
          external: "090 · FNB Business Cheque",
          from: { code: "610", name: "Bank — operating" },
          to: { code: "611", name: "Bank — FNB operating" },
          txns: 1284,
        },
        {
          external: "091 · FNB Call Account",
          from: { code: "612", name: "Bank — call" },
          to: { code: "613", name: "Bank — FNB call" },
          txns: 96,
        },
        {
          external: "094 · FNB Credit Card",
          from: { code: "620", name: "Credit card" },
          to: { code: "621", name: "Bank — FNB credit card" },
          txns: 412,
        },
      ],
    },
    live: {
      note: "Remapping rewrites the target account on future imports only. Historic postings keep their original account.",
      cols: ["Mapping", "Currently", "After"],
      rows: [
        {
          code: "090",
          name: "FNB Business Cheque",
          cls: "bank",
          nowText: "610 Bank — operating",
          afterText: "611 Bank — FNB operating",
        },
        {
          code: "091",
          name: "FNB Call Account",
          cls: "bank",
          nowText: "612 Bank — call",
          afterText: "613 Bank — FNB call",
        },
        {
          code: "094",
          name: "FNB Credit Card",
          cls: "bank",
          nowText: "620 Credit card",
          afterText: "621 Bank — FNB credit card",
        },
      ],
    },
    checks: [
      ok(
        "coa",
        "Target accounts exist",
        "611, 613 and 621 are active in ZA-COA-v7.",
      ),
      ok(
        "reconcile",
        "No open reconciliation",
        "Feed 090 last reconciled 2026-07-26 — nothing part-matched.",
      ),
      pending(
        "outstanding",
        "1,792 historic transactions keep old accounts",
        "Only imports after approval use the new mapping. Backfill is a separate playbook.",
      ),
      pending(
        "rule",
        "Two bank rules reference 610",
        "bank-rule-fees and bank-rule-sweep will need the new code.",
      ),
    ],
    timeline: [
      {
        icon: "reconcile",
        who: "Connector sync",
        what: "detected three renamed accounts in the Xero chart pull.",
        at: "2026-07-27 03:15:20 UTC",
      },
      {
        icon: "bank_rule",
        who: "System",
        what: "proposed a like-for-like remap, preserving class and currency.",
        at: "2026-07-27 03:15:21 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy connector-xero",
        what: "mapping changes are never auto-applied.",
        at: "2026-07-27 03:15:21 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "op": "update_mapping",\n  "mapping": "XERO-ZA-MAP",\n  "changes": [\n    { "external": "090", "from": "610", "to": "611" },\n    { "external": "091", "from": "612", "to": "613" },\n    { "external": "094", "from": "620", "to": "621" }\n  ],\n  "apply_to": "future_imports"\n}`,
    },
  },
  {
    id: "xero-push-fy2025~4f0ab21d7e55",
    kind: "upstream",
    icon: "posting",
    direction: "outbound",
    title: "Push 12 close journals to Xero · FY2025",
    subtitle: "Upstream write · manual journals",
    amount: 1284905.4,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "connector-xero",
    ruleId: "b3c9e77f-1a24-4f80-bb61-90d7c4e5a118",
    ruleVersion: 3,
    targetType: "period",
    targetId: "FY2025",
    period: "FY2025",
    connector: "Xero",
    idempotency: "rule:0ab7f4c9912e5db38a67c0154fe2b3d8991a4c77e5b60213",
    sourceRecords: ["period:FY2025", "batch:CLOSE-FY2025-03"],
    requestedBy: "R. Botha",
    created: "2026-07-27 08:44:09 UTC",
    age: "4h",
    change: {
      system: "Xero",
      endpoint: "POST /api.xro/2.0/ManualJournals",
      tenant: "Merivio Trading (Pty) Ltd",
      mode: "Idempotent batch · 12 documents",
      docs: [
        {
          ref: "JNL-2025-0181",
          narr: "Depreciation · Dec 2025",
          amount: 48210.0,
          status: "ready",
        },
        {
          ref: "JNL-2025-0182",
          narr: "Accrued audit fees",
          amount: 96000.0,
          status: "ready",
        },
        {
          ref: "JNL-2025-0183",
          narr: "FX revaluation · USD creditors",
          amount: 12488.9,
          status: "ready",
        },
        {
          ref: "JNL-2025-0184",
          narr: "Current income tax FY2025",
          amount: 32592.17,
          status: "waiting",
        },
        {
          ref: "JNL-2025-0185",
          narr: "Leave pay provision",
          amount: 41300.0,
          status: "ready",
        },
      ],
      more: 7,
      retries: 0,
      lastAttempt: "—",
    },
    live: {
      note: "Xero rejects writes into a locked period. Confirm the FY2025 lock date before the batch runs.",
      cols: ["Remote check", "Xero now", "After push"],
      rows: [
        {
          code: "FY2025",
          name: "Period lock",
          cls: "sub",
          nowText: "Open · locks 2026-09-30",
          afterText: "Open",
        },
        {
          code: "MJ",
          name: "Manual journals in FY2025",
          cls: "sub",
          nowText: "168",
          afterText: "180",
        },
      ],
    },
    checks: [
      ok(
        "paid",
        "11 of 12 documents ready",
        "All balanced, all accounts mapped.",
      ),
      ok(
        "reconcile",
        "Connector healthy",
        "Xero token valid · last successful write 2026-07-27 06:02 UTC.",
      ),
      pending(
        "awaiting",
        "One document waits on this queue",
        "JNL-2025-0184 depends on the ITR14 approval above.",
      ),
      ok(
        "rule",
        "Idempotent batch",
        "Each document carries a key — a retry cannot duplicate a journal.",
      ),
    ],
    timeline: [
      {
        icon: "journal",
        who: "R. Botha",
        what: "closed the FY2025 batch and queued it for upstream write.",
        at: "2026-07-27 08:44:09 UTC",
      },
      {
        icon: "posting",
        who: "Connector xero",
        what: "validated 12 documents against the Xero chart — no unmapped accounts.",
        at: "2026-07-27 08:44:31 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy connector-xero",
        what: "upstream writes above 1,000,000.00 require approval.",
        at: "2026-07-27 08:44:31 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "op": "upstream_write",\n  "system": "xero",\n  "endpoint": "/api.xro/2.0/ManualJournals",\n  "batch": "CLOSE-FY2025-03",\n  "documents": 12,\n  "idempotent": true\n}`,
    },
  },
  {
    id: "ap-bill-aws~77ce0125f9a1",
    kind: "transaction",
    icon: "bill",
    direction: "inbound",
    title: "Bill AWS-EMEA-0726 · Amazon Web Services",
    subtitle: "Purchase bill · USD 9,842.63",
    amount: 178150.71,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "ap-cloud-spend",
    ruleId: "9de1a70b-52c4-4bb8-9a06-c2f7e0a41d63",
    ruleVersion: 6,
    targetType: "bill",
    targetId: "AWS-EMEA-0726",
    period: "Jul 2026",
    connector: "Xero",
    idempotency: "rule:7b103fa9c48d2e6510bb7cf34a90d251ee87c0b4419fa236",
    sourceRecords: ["invoice:AWS-EMEA-0726"],
    requestedBy: "Rule engine",
    created: "2026-07-27 01:05:47 UTC",
    age: "11h",
    change: {
      docType: "Purchase bill",
      number: "AWS-EMEA-0726",
      contact: "Amazon Web Services EMEA",
      contactRef: "CON-0007",
      date: "2026-07-26",
      due: "2026-08-25",
      status: "Draft",
      terms: "Net 30 · USD at 18.10",
      lines: [
        {
          code: "470",
          name: "Cloud hosting",
          cls: "expense",
          icon: "expenses",
          desc: "EC2, EKS and EBS · Jul 2026",
          qty: 1,
          unit: 142980.4,
          net: 142980.4,
          tax: 21447.06,
          gross: 164427.46,
        },
        {
          code: "471",
          name: "Data transfer",
          cls: "expense",
          icon: "expenses",
          desc: "Egress · 82 TB",
          qty: 82,
          unit: 145.6,
          net: 11939.2,
          tax: 1790.88,
          gross: 13730.08,
        },
      ],
      totals: { net: 154919.6, tax: 23237.94, gross: 178157.54 },
    },
    live: {
      note: "The USD rate is fixed at the bill date. Re-check before approving if the rate moved materially.",
      cols: ["Account", "Ledger now", "After posting"],
      rows: [
        {
          code: "800",
          name: "Accounts payable",
          cls: "liability",
          now: -96420.18,
          after: -274577.72,
        },
        {
          code: "470",
          name: "Cloud hosting",
          cls: "expense",
          now: 1042118.9,
          after: 1185099.3,
        },
      ],
    },
    checks: [
      ok(
        "trial_balance",
        "Bill totals reconcile",
        "Net 154,919.60 + VAT 23,237.94 = 178,157.54.",
      ),
      ok("fx_rate", "Rate sourced", "USD/ZAR 18.10 · SARB mid at 2026-07-26."),
      ok("contact", "Supplier known", "CON-0007 · 41 bills, no disputes open."),
      pending(
        "outstanding",
        "Above cloud budget",
        "Jul cloud spend is 8.4% over the 165,000.00 budget line.",
      ),
    ],
    timeline: [
      {
        icon: "bill",
        who: "Connector xero",
        what: "imported the AWS invoice from the supplier mailbox.",
        at: "2026-07-27 01:05:47 UTC",
      },
      {
        icon: "rule",
        who: "Rule engine",
        what: "coded 2 lines to 470 and 471 from the historical pattern.",
        at: "2026-07-27 01:05:49 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy ap-cloud-spend",
        what: "held the bill — over budget for the period.",
        at: "2026-07-27 01:05:49 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "rule": "ap-bill-aws~77ce0125f9a1",\n  "source": "supplier_mailbox",\n  "currency": "USD",\n  "rate": "18.10",\n  "budget_line": "cloud",\n  "over_budget_pct": 8.4\n}`,
    },
  },
  {
    id: "fx-reval-2026-06~1d90ab44c218",
    kind: "journal",
    icon: "revaluation",
    direction: "internal",
    title: "FX revaluation · June 2026",
    subtitle: "Journal · 4 lines · unrealised",
    amount: 12488.9,
    currency: "ZAR",
    state: "proposed",
    readiness: "Ready",
    policy: "Approval required",
    module: "fx-revaluation",
    ruleId: "e0f7b214-33aa-4c60-91cd-7b4d5e0a2f97",
    ruleVersion: 2,
    targetType: "period",
    targetId: "2026-06",
    period: "Jun 2026",
    connector: "Xero",
    idempotency: "rule:2ce8b7104a3f95d6e01c7bb428fa6390d51e7c9042ab8f31",
    sourceRecords: ["period:2026-06"],
    requestedBy: "Rule engine",
    created: "2026-07-01 02:00:04 UTC",
    age: "26d",
    change: {
      name: "Unrealised FX · USD creditors and debtors",
      date: "2026-06-30",
      status: "Draft",
      debit: 12488.9,
      credit: 12488.9,
      lines: [
        {
          code: "499",
          name: "Unrealised FX loss",
          cls: "expense",
          icon: "expenses",
          dir: "debit",
          desc: "USD creditors restated at 18.10",
          net: 12488.9,
          tax: 0,
          gross: 12488.9,
        },
        {
          code: "800",
          name: "Accounts payable",
          cls: "liability",
          icon: "ap",
          dir: "credit",
          desc: "Restatement of USD balances",
          net: -12488.9,
          tax: 0,
          gross: -12488.9,
        },
      ],
    },
    live: {
      note: "Revaluation must run against the closing rate. A later rate correction means this journal has to be reversed and re-run.",
      cols: ["Account", "Ledger now", "After posting"],
      rows: [
        {
          code: "499",
          name: "Unrealised FX loss",
          cls: "expense",
          now: 41208.11,
          after: 53697.01,
        },
        {
          code: "800",
          name: "Accounts payable",
          cls: "liability",
          now: -96420.18,
          after: -108909.08,
        },
      ],
    },
    checks: [
      ok("trial_balance", "Debits equal credits", "12,488.90 both sides."),
      ok("fx_rate", "Closing rate applied", "USD/ZAR 18.10 · SARB close 2026-06-30."),
      pending(
        "outstanding",
        "Sat 26 days in the queue",
        "June closes 2026-07-31. Approve or reject before month-end lock.",
      ),
      ok(
        "reversal",
        "Auto-reverses",
        "Journal reverses on 2026-07-01 as an unrealised entry.",
      ),
    ],
    timeline: [
      {
        icon: "revaluation",
        who: "Rule engine",
        what: "restated USD balances at the June closing rate.",
        at: "2026-07-01 02:00:04 UTC",
      },
      {
        icon: "journal",
        who: "System",
        what: "generated a self-reversing journal for 2026-07-01.",
        at: "2026-07-01 02:00:05 UTC",
      },
      {
        icon: "awaiting",
        who: "Policy fx-revaluation",
        what: "routed to approval — unrealised movements are never auto-posted.",
        at: "2026-07-01 02:00:05 UTC",
      },
    ],
    payloads: {
      "Request payload": `{\n  "rule": "fx-reval-2026-06~1d90ab44c218",\n  "period": "2026-06",\n  "rate_source": "SARB",\n  "rate": "18.10",\n  "auto_reverse": "2026-07-01"\n}`,
    },
  },
  {
    id: "ar-invoice-autoraise~b2210ce49f07",
    kind: "transaction",
    icon: "invoice",
    direction: "outbound",
    title: "Sales invoice INV-2039 · Kalahari Freight",
    subtitle: "Raise and send · net 30",
    amount: 9430.0,
    currency: "ZAR",
    state: "approved",
    readiness: "Posted",
    policy: "Approval required",
    module: "ar-billing",
    ruleId: "2b41c7de-90aa-4c11-9d3e-b5c1a4471f02",
    ruleVersion: 4,
    targetType: "contract",
    targetId: "CTR-1102",
    period: "Jun 2026",
    connector: "Xero",
    idempotency: "rule:aa41f0c7728b95de6104cb3f2870ad91ee5c47b0139fa628",
    sourceRecords: ["contract:CTR-1102"],
    requestedBy: "Rule engine",
    created: "2026-07-24 04:02:08 UTC",
    age: "3d",
    resolvedBy: "R. Botha",
    resolvedAt: "2026-07-24 09:11:52 UTC",
    change: {
      docType: "Sales invoice",
      number: "INV-2039",
      contact: "Kalahari Freight CC",
      contactRef: "CON-0388",
      date: "2026-06-30",
      due: "2026-07-30",
      status: "Posted",
      terms: "Net 30",
      lines: [
        {
          code: "200",
          name: "Sales — platform fees",
          cls: "revenue",
          icon: "income",
          desc: "Monthly platform fee · June 2026",
          qty: 1,
          unit: 8200,
          net: 8200,
          tax: 1230,
          gross: 9430,
        },
      ],
      totals: { net: 8200, tax: 1230, gross: 9430 },
    },
    checks: [
      ok(
        "paid",
        "Posted to Xero",
        "INV-2039 created 2026-07-24 · emailed to billing@kalaharifreight.co.za.",
      ),
    ],
    timeline: [
      {
        icon: "rule",
        who: "Rule engine",
        what: "drafted INV-2039 from contract CTR-1102.",
        at: "2026-07-24 04:02:08 UTC",
      },
      {
        icon: "paid",
        who: "R. Botha",
        what: "approved the invoice. Posted and sent.",
        at: "2026-07-24 09:11:52 UTC",
      },
    ],
    payloads: {},
  },
  {
    id: "coa-marketing-split~30ff81b5ea42",
    kind: "account",
    icon: "coa",
    direction: "outbound",
    title: "New account 452 · Paid acquisition",
    subtitle: "Chart of accounts · expense",
    amount: null,
    currency: "ZAR",
    state: "rejected",
    readiness: "Closed",
    policy: "Approval required",
    module: "coa-governance",
    ruleId: "61b0f2a7-9d3c-4a71-b8e4-05fd7c1a9033",
    ruleVersion: 1,
    targetType: "chart",
    targetId: "ZA-COA-v7",
    period: "Jul 2026",
    connector: "Xero",
    idempotency: "rule:5d0c9317ea4b8f2601bc7ff4a3927d15cc0b8e4471fa2039",
    sourceRecords: ["chart:ZA-COA-v7"],
    requestedBy: "T. Nkosi",
    created: "2026-07-20 14:22:00 UTC",
    age: "7d",
    resolvedBy: "R. Botha",
    resolvedAt: "2026-07-20 16:05:11 UTC",
    change: {
      op: "create",
      code: "452",
      name: "Paid acquisition",
      cls: "expense",
      type: "Operating expense",
      taxRate: "VAT on expenses (15%)",
      parent: "450 · Marketing",
      currency: "ZAR",
      description: "Split paid channel spend out of the general marketing account.",
      flags: [
        ["Show on dashboard", "Yes"],
        ["Enable payments", "No"],
        ["Lock to rule postings", "No"],
      ],
      usedBy: [],
    },
    checks: [
      bad(
        "overdue",
        "Rejected",
        "Use tracking categories for channel splits — the chart stays flat below 450.",
      ),
    ],
    timeline: [
      {
        icon: "coa",
        who: "T. Nkosi",
        what: "requested a new expense account for paid channels.",
        at: "2026-07-20 14:22:00 UTC",
      },
      {
        icon: "reversal",
        who: "R. Botha",
        what: "rejected — channel detail belongs in tracking categories, not the chart.",
        at: "2026-07-20 16:05:11 UTC",
      },
    ],
    payloads: {},
  },
];
